name: Rename

on:
  push:
    branches:
      - main

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Rename
        run: |
          mv libs/ libraries/
          mv natives/ bin/
